apiVersion: v1
name: kubernetes-external-secrets
version: 2.2.3
appVersion: 2.2.3
description: Kubernetes External Secrets CustomResourceDefinition
keywords:
  - kubernetes-external-secrets
  - secrets
home: https://github.com/pearsontechnology/kubernetes-external-secrets
sources:
  - http://external-charts.prsn.io
maintainers:
  - name: ishansd94
    email: ishansd94@gmail.com
